Default vagrantfile template as template var
hashicorp/packer-plugin-vagrant pull request #59
Opened 2022-08-10 17:32 UTC by dangra

The whole point is to pass a vagrantfile template that can extend the default template.
As a consequence, this PR also includes tests for `template` source field not tested until now.

```hcl
source "vagrant" "foo" {
  communicator         = "ssh"
  source_path          = "some/box"
  provider             = "virtualbox"
  template             = "Vagrantfile.tpl"
}
```

```ruby
# Vagrantfile.tpl
{{ .DefaultTemplate }}

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
  end
end
```

2022-08-10 17:32 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-vagrant?pullRequest=59)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-vagrant?pullRequest=59)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-vagrant?pullRequest=59).</sub>

2023-01-10 22:10 UTC, dangra commented
I still find this useful and it comes with tests to validate it works as expected :)

2023-09-25 14:25 UTC, nywilken commented
Hi @dangra apologies for the longer then normal review process. We haven't had the chance to prioritize this review. We have however selected the PR and will provide feedback if you are still interested in working on the change. Thanks!

2023-09-25 15:02 UTC, dangra commented
I still rely on a workaround so will be happy to discuss further improvements to get this merged

2023-10-18 11:01 UTC, nywilken requested changes
Thanks again @dangra the changes look good to me so far. From looking at the code and description you are essentially making the template variable `{{.DefaultTemplate}}` available for users. Which gives the option of generating a template file containing multiple version configuration blocks like the following:

```
Vagrant.configure("2") do |config|
  # Generated by the vagrant builder.... contents of {{.DefaultTemplate}}
end

Vagrant.configure("2") do |config|
  # some other pre-exisiting configuration 
end
```

Would you mind sharing details on your use case so I can better understand the why.



That said, If you could add a comment to the builder file [here](https://github.com/hashicorp/packer-plugin-vagrant/blob/c8761085dca48c4d09babdf1a5bb9c566b77c3be/builder/vagrant/builder.go#L107C78-L107C78) for the `{{.DefaultTemplate}}`. Maybe something like example below and run `make generate` that would update all the documentation files. 

```go 
+       // Alternatively, the template variable `{{.DefaultTemplate}}` is available for
+       // use if you wish extend the default generated template.
```

I'm also happy to update the docs for you on this PR but I would like to understand the use case better to add a little more light as to why in the docs.

2023-10-18 12:47 UTC, dangra commented
> That said, If you could add a comment to the builder file [here](https://github.com/hashicorp/packer-plugin-vagrant/blob/c8761085dca48c4d09babdf1a5bb9c566b77c3be/builder/vagrant/builder.go#L107C78-L107C78) for the `{{.DefaultTemplate}}`. Maybe something like example below and run `make generate` that would update all the documentation files.
> 
> ```go
> +       // Alternatively, the template variable `{{.DefaultTemplate}}` is available for
> +       // use if you wish extend the default generated template.
> ```

Done

2023-10-18 14:10 UTC, nywilken approved these changes
Great thanks for the update. I rebased and pushed up the changes. I will merge and release once all goes green.

2023-10-18 15:14 UTC, merged